apiVersion: v1
kind: Service
metadata:
  name: utrains-service
spec:
  type: NodePort
  selector:
    name: utrains
  ports:
    - port: 80
      targetPort: 80
      # optional
      nodePort: 30007 
