apiVersion: v1
kind: Pod
metadata:
  name: utrains
 # namespace: dev
  labels:
   app: utrains
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sku
            operator: In
            values:
            - small       
  containers:
    - name: utrains-app
      image: httpd
