apiVersion: v1
kind: Pod
metadata:
  name: utrains
#  namespace: dev
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: httpd
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - web
        topologyKey: "kubernetes.io/hostname"
