apiVersion: v1
kind: Pod
metadata:
  name: utrains1
#  namespace: dev
  labels:
   app: utrains1
spec:
  containers:
    - name: utrains-app
      image: httpd
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - web
        topologyKey: "kubernetes.io/hostname"
